/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.devring.workshop;

public class ClassWithConditions {
    enum OsName {
        WINDOWS,
        LINUX,
        MAC,
        UNKNOWN
    }

    public OsName getOsName() {
        String osName = System.getProperty("os.name");

        if (osName.startsWith("Windows")) {
            return OsName.WINDOWS;
        } if (osName.startsWith("Mac")) {
            return OsName.MAC;
        } else if ( osName.equals("Linux")) {
            return OsName.LINUX;
        } else return OsName.UNKNOWN;
    }

}
