/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.devring.workshop;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test 
    private void appHasAGreeting() {
        //given
        App classUnderTest = new App();
        //when
        String actual = classUnderTest.getGreeting();
        //then
        assertNotNull(actual, "app should have a greeting");
    }

    //TODO: check if greeting is equal to expected
    // @Test 
    private void appShouldHaveSpecificGreeteng() {
    }
}
